// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB0IlPlG7JHA7VXwqDwsbWVJL4nZrc8Us',
    appId: '1:372195678596:web:0638e62248015894eee5d1',
    messagingSenderId: '372195678596',
    projectId: 'housie-game-be0b8',
    authDomain: 'housie-game-be0b8.firebaseapp.com',
    databaseURL: 'https://housie-game-be0b8-default-rtdb.firebaseio.com/',
    storageBucket: 'housie-game-be0b8.firebasestorage.app',
    measurementId: 'G-YL8ERTRLF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOn911kxdtlnwX625MvB8xcGJzAg3mx8k',
    appId: '1:372195678596:android:46eeba720df318d9eee5d1',
    messagingSenderId: '372195678596',
    projectId: 'housie-game-be0b8',
    databaseURL: 'https://housie-game-be0b8-default-rtdb.firebaseio.com/',
    storageBucket: 'housie-game-be0b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoznK4JjrBTgmJfQqC2hlXp-a4Vs0SOms',
    appId: '1:372195678596:ios:516a102cb0bea68beee5d1',
    messagingSenderId: '372195678596',
    projectId: 'housie-game-be0b8',
    databaseURL: 'https://housie-game-be0b8-default-rtdb.firebaseio.com/',
    storageBucket: 'housie-game-be0b8.firebasestorage.app',
    iosBundleId: 'com.example.housieProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoznK4JjrBTgmJfQqC2hlXp-a4Vs0SOms',
    appId: '1:372195678596:ios:516a102cb0bea68beee5d1',
    messagingSenderId: '372195678596',
    projectId: 'housie-game-be0b8',
    databaseURL: 'https://housie-game-be0b8-default-rtdb.firebaseio.com/',
    storageBucket: 'housie-game-be0b8.firebasestorage.app',
    iosBundleId: 'com.example.housieProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB0IlPlG7JHA7VXwqDwsbWVJL4nZrc8Us',
    appId: '1:372195678596:web:b7c22325d59ead2deee5d1',
    messagingSenderId: '372195678596',
    projectId: 'housie-game-be0b8',
    authDomain: 'housie-game-be0b8.firebaseapp.com',
    databaseURL: 'https://housie-game-be0b8-default-rtdb.firebaseio.com/',
    storageBucket: 'housie-game-be0b8.firebasestorage.app',
    measurementId: 'G-TQ9DJ6WXDB',
  );
}
